name: build
on: [push, pull_request]
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt update ; sudo apt install xz-utils
    - run: curl -sL http://downloads.arduino.cc/arduino-1.8.19-linux64.tar.xz | tar -xzf -
    - run: ls -l
